#!/usr/local/bin/perl
# ---------------------------------------------------------------------------
# Copyright (C) 2008-2017 TJ Saunders <tj@castaglia.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Suite 500, Boston, MA 02110-1335, USA.
# ---------------------------------------------------------------------------

use strict;
use utf8;

use File::Basename qw(basename);
use Getopt::Long;
use Mail::Sendmail;
use MIME::Base64 qw(encode_base64);
use Time::HiRes qw(usleep);

my $program = basename($0);

# Add the PID file path
my $pid_file = '/var/run/ftpmail.pid';

my $opts = {};
GetOptions($opts, 'attach-file', 'fifo=s', 'from=s', 'help', 'ignore-users=s',
  'log=s', 'recipient=s@', 'upload-recipient=s@', 'download-recipient=s@',
  'sleep=s', 'smtp-server=s', 'subject=s', 'watch-users=s', 'auth=s',
  'pid=s');  # Add the --pid option

if ($opts->{help}) {
  usage();
  exit 0;
}

# Update the PID file location if provided via the --pid option
$pid_file = $opts->{pid} if defined $opts->{pid};

# Write the PID file
write_pid_file($pid_file);

unless ($opts->{fifo}) {
  print STDERR "$program: missing required --fifo parameter\n";
  exit 1;
}
my $fifo = $opts->{fifo};

unless ($opts->{from}) {
  print STDERR "$program: missing required --from parameter\n";
  exit 1;
}
my $from = $opts->{from};

unless ($opts->{recipient} ||
        $opts->{'upload-recipient'}) {
  print STDERR "$program: missing required --recipient (or --upload-recipient) parameter\n";
  exit 1;
}
my $upload_recipients = $opts->{recipient};

# The --upload-recipient list takes precedence over the (deprecated)
# --recipient list.
if (defined($opts->{'upload-recipient'})) {
   $upload_recipients = $opts->{'upload-recipient'};
}

my $download_recipients = undef;
if (defined($opts->{'download-recipient'})) {
  $download_recipients = $opts->{'download-recipient'};
}

unless ($opts->{'smtp-server'}) {
  print STDERR "$program: missing required --smtp-server parameter\n";
  exit 1;
}
my $smtp_server = $opts->{'smtp-server'};

my $smtp_auth;
if ($opts->{'auth'}) {
  eval { $smtp_auth = get_auth_info($opts->{'auth'}) };
  if ($@) {
    my $ex = $@;
    print STDERR "$program: unable to obtain SMTP auth info: $ex\n";
    exit 1;
  }
}

while (1) {
  open(FIFO, $fifo) || die "$program: failed to open $fifo: $!\n";
  while (<FIFO>) {
    my $content = $_;

    chomp $content;
    if ($content =~ /^\s*$/) {
      # Ignore empty lines
      next;
    }
    elsif ($content =~ /^\s*#/) {
      # Ignore comment lines
      next;
    }

    # Split the content into an array of fields
    my @fields = split(/\|/, $content);

    # Remove leading/trailing whitespace from each field
    @fields = map { s/^\s+|\s+$//g; $_ } @fields;

    my $filename = $fields[0];
    my $filesize = $fields[1];
    my $username = $fields[2];
    my $hostname = $fields[3];
    my $timestamp = $fields[4];
    my $type = $fields[5];
    my $file_path = $fields[6];

    # Send the email
    my $mail = {
      To      => $upload_recipients,
      From    => $from,
      Subject => $opts->{subject} || "File Uploaded",
      Message => "A file has been uploaded via FTP to the server.\n\n" .
                 "Filename: $filename\n" .
                 "Filesize: $filesize bytes\n" .
                 "Username: $username\n" .
                 "Hostname: $hostname\n" .
                 "Timestamp: $timestamp\n" .
                 "Type: $type\n",
      'Content-Type' => 'text/plain; charset=utf-8',
    };

    # Add the download recipients if specified
    if ($download_recipients) {
      $mail->{'Cc'} = $download_recipients;
    }

    # Attach the file if requested
    if ($opts->{'attach-file'}) {
      my $attachment = {
        path        => $file_path,
        type        => $type,
        encoding    => 'base64',
        disposition => 'attachment',
      };
      $mail->{body} = encode_base64(read_file($file_path));
      $mail->{'Content-Type'} = 'application/octet-stream';
      $mail->{'Content-Disposition'} = 'attachment; filename="' . $filename . '"';
      $mail->{'Content-Transfer-Encoding'} = 'base64';
    }

    eval {
      sendmail(%$mail, Smtp => $smtp_server, $smtp_auth ? %$smtp_auth : ());
    };
    if ($@) {
      my $ex = $@;
      print STDERR "$program: failed to send email: $ex\n";
      exit 1;
    }

    usleep($opts->{sleep} || 0);
  }
  close(FIFO);
}

sub read_file {
  my ($file_path) = @_;
  local $/ = undef;
  open(my $file, '<:encoding(utf8)', $file_path) or die "$program: failed to open file $file_path: $!";
  my $content = <$file>;
  close($file);
  return $content;
}

sub get_auth_info {
  my ($auth_file) = @_;
  my $auth = {};
  open(AUTH, $auth_file) || die "$program: failed to open auth file $auth_file: $!\n";
  while (<AUTH>) {
    my $line = $_;
    chomp($line);
    my ($key, $value) = split(/\s+/, $line, 2);
    $auth->{$key} = $value;
  }
  close(AUTH);
  return $auth;
}

sub write_pid_file {
  my ($pid_file) = @_;
  open(PID, ">$pid_file") || die "$program: failed to write PID file $pid_file: $!\n";
  print PID "$$\n";
  close(PID);
}

sub usage {
  print <<"USAGE";
Usage: $program --fifo <path> --from <address> [--ignore-users <users>]
                --log <path> [--recipient <address>]
                --smtp-server <server> [--subject <subject>]
                [--watch-users <users>] [--attach-file]
                [--upload-recipient <address>] [--download-recipient <address>]
                [--sleep <microseconds>] [--auth <file>] [--pid <path>]
       $program --help

  --fifo <path>          Path to the FIFO file to monitor.
  --from <address>       The email address to use as the "From" address in the emails sent.
  --ignore-users <users> Comma-separated list of usernames to ignore (optional).
  --log <path>           Path to the log file (optional).
  --recipient <address>  The email address(es) to receive the upload notifications.
  --smtp-server <server> The SMTP server to use for sending email notifications.
  --subject <subject>    Subject line for the email notifications (optional).
  --watch-users <users>  Comma-separated list of usernames to watch (optional).
  --attach-file          Attach the uploaded file to the email (optional).
  --upload-recipient <address>
                         The email address(es) to receive the upload notifications (deprecated).
  --download-recipient <address>
                         The email address(es) to receive the download notifications (optional).
  --sleep <microseconds> Sleep duration in microseconds between processing messages (optional).
  --auth <file>          Path to a file containing SMTP authentication information (optional).
  --pid <path>           Path to the PID file (optional).
  --help                 Show this help message.
USAGE
}
