--- pyproject.toml.orig	2026-07-05 10:08:00 UTC
+++ pyproject.toml
@@ -29,7 +29,7 @@ description = "A cross-platform curses-based monitorin
 dynamic = ["version"]
 keywords = ["cli", "curses", "monitoring", "system"]
-license = "LGPL-3.0-only"
+license = {text = "LGPL-3.0-only"}
 name = "Glances"
 readme = "README-pypi.rst"
 requires-python = ">=3.10"
