COMMENT = Mail ports maintained by raivo@lehma.com

SUBDIR += dovecot-xaps-daemon
SUBDIR += dovecot-xaps-plugin
SUBDIR += postfixadmin-current
SUBDIR += py-postfix-mta-sts-resolver
SUBDIR += roundcube
SUBDIR += roundcube-carddav
SUBDIR += roundcube-contextmenu
SUBDIR += roundcube-html5_notifier

.include <bsd.port.subdir.mk>
