--- cargo-crates/v8-150.4.0/build/config/BUILD.gn.orig	2026-06-10 02:22:19 UTC
+++ cargo-crates/v8-150.4.0/build/config/BUILD.gn
@@ -216,7 +216,7 @@ config("default_libs") {
     # Targets should choose to explicitly link frameworks they require. Since
     # linking can have run-time side effects, nothing should be listed here.
     libs = []
-  } else if (is_linux || is_chromeos) {
+  } else if (is_linux || is_chromeos || is_freebsd) {
     libs = [
       "pthread",
     ]
