--- cargo-crates/v8-150.4.0/build/config/compiler_cpu_abi.gn.orig	2026-06-10 02:22:19 UTC
+++ cargo-crates/v8-150.4.0/build/config/compiler_cpu_abi.gn
@@ -48,7 +48,8 @@
 if ((is_posix && !is_apple) || is_fuchsia) {
   # simplicity we always explicitly set the architecture.
   if (current_cpu == "x64") {
-    if (is_clang && !is_android && !is_fuchsia && !is_chromeos_device) {
+    if (is_clang && !is_android && !is_fuchsia && !is_chromeos_device &&
+        !is_freebsd) {
       cpu_abi_cflags += [ "--target=x86_64-unknown-linux-gnu" ]
       cpu_abi_ldflags += [ "--target=x86_64-unknown-linux-gnu" ]
     } else {
