--- cargo-crates/v8-150.4.0/build/config/compiler/BUILD.gn.orig	2026-06-10 02:22:19 UTC
+++ cargo-crates/v8-150.4.0/build/config/compiler/BUILD.gn
@@ -540,7 +540,7 @@ config("compiler") {
 
   # Linux/Android/Fuchsia common flags setup.
   # ---------------------------------
-  if (is_linux || is_chromeos || is_android || is_fuchsia) {
+  if (is_linux || is_chromeos || is_android || is_fuchsia || is_freebsd) {
     asmflags += [ "-fPIC" ]
     cflags += [ "-fPIC" ]
     ldflags += [ "-fPIC" ]
